<?php
/**
 * Class: BlogPostExtension
 * Summary
 * Description
 * @author: richardrudy
 * @package   * @version:
 */

use SilverStripe\ORM\DataExtension;


class BlogPostExtension extends DataExtension
{
    private static $db = [
        "Featured" => "Boolean"
    ];

    public function updateCMSFields(\SilverStripe\Forms\FieldList $fields)
    {

        $fields->addFieldToTab("Root.PostOptions", \SilverStripe\Forms\CheckboxField::create('Featured'));
        parent::updateCMSFields($fields); // TODO: Change the autogenerated stub
    }
}