<?php
/**
 * Class: MenuItemExtension
 * Summary
 * Description
 * @author: richardrudy
 * @version:
 */

use NathanCox\CodeEditorField\CodeEditorField;

class MenuItemExtension extends \SilverStripe\ORM\DataExtension
{
    private static $db = [
        'SVGCode' => 'HTMLText'
    ];


    public function updateCMSFields(\SilverStripe\Forms\FieldList $fields)
    {
        $svgField = CodeEditorField::create('SVGCode', 'SVG')
                                   ->setRows(30)
                                   ->setMode('svg')
                                   ->setTheme('twilight');

        $fields->push($svgField);

        parent::updateCMSFields($fields); // TODO: Change the autogenerated stub
    }

}

