<?php

namespace {

    use Bummzack\SortableFile\Forms\SortableUploadField;
    use GoToMarketers\Model\DataObjects\Taxonomy;
    use NathanCox\CodeEditorField\CodeEditorField;
    use SilverStripe\AssetAdmin\Forms\UploadField;
    use SilverStripe\CMS\Model\SiteTree;
    use SilverStripe\Assets\Image;
    use SilverStripe\Forms\DropdownField;
    use SilverStripe\Forms\HTMLEditor\HTMLEditorField;
    use SilverStripe\Forms\TextField;
    use UncleCheese\DisplayLogic\Forms\Wrapper;

    class Page extends SiteTree
    {
        private static $db = [
            "HeaderType" => "Varchar",
            "HeaderContent" => "HTMLText",
            "HeaderClasses" => "Varchar(255)",
            "ExtraCSS" => "HTMLText",
            "ExtraJS" => "HTMLText",
            "ExtraJSFooter" => "HTMLText",
            "ExtraTagsFooter" => "HTMLText"
        ];

        private static $has_one = [
            "HeaderImage" => Image::class,
            "FeatureImage" => Image::class
        ];

        private static $many_many = [
            "PillImages" => Image::class,
            "Tags" => Taxonomy::class
        ];

        private static $many_many_extraFields = [
            'PillImages' => ['SortOrder' => 'Int']
        ];

        private static $owns = [
            'HeaderImage',
            'FeatureImage',
            'PillImages'
        ];

        public function getCMSFields()
        {
            $fields = parent::getCMSFields(); // TODO: Change the autogenerated stub

            $headerTypes = ['' => 'Default', 'simple-header' => "Simple", 'hero-header' => 'Hero', 'pill-header-4' => 'Pill 4', 'pill-header-7' => 'Pill 7'];

            $fields->insertAfter(
                "MenuTitle",
                DropdownField::create(
                    "HeaderType",
                    null,
                    $headerTypes
                )
            );

            $headerContent = Wrapper::create(
                HTMLEditorField::create('HeaderContent')
            );

            $headerBackground = UploadField::create("HeaderImage")->setFolderName('header-images');
            $pillImagesField = SortableUploadField::create("PillImages");
            if($this->URLSegment) {
                $pillImagesField->setFolderName('header-images/pills/'.$this->URLSegment);
            } else {
                $pillImagesField->setFolderName('header-images/pills');
            }


            $pillImages = Wrapper::create(
                $pillImagesField
            );



            $headerContent->displayIf('HeaderType')->contains('header');
            $pillImages->displayIf('HeaderType')->contains('pill');

            $headerClasses = TextField::create('HeaderClasses');

            if($this->hasExtension('DNADesign\Elemental\Extensions\ElementalPageExtension')) {
                $fieldInsert = "ElementalArea";
            } else {
                $fieldInsert = 'Content';
            }

            $fields->addFieldsToTab(
                'Root.Main',
                array($headerContent, $pillImages, $headerBackground, $headerClasses),
                "Content"
            );


            return $fields;
        }


        public function getSettingsFields()
        {
            $fields = parent::getSettingsFields(); // TODO: Change the autogenerated stub

            $fields->addFieldToTab(
                "Root.Code",
                CodeEditorField::create('ExtraCSS', 'Page Specific CSS')
                               ->addExtraClass('stacked')
                               ->setRows(30)
                               ->setMode('scss')
                               ->setTheme('twilight')
            );

            $fields->addFieldToTab(
                "Root.Code",
                CodeEditorField::create('ExtraJS', 'Page Specific JavaScript DO NOT INCLUDE <script></script>')
                               ->addExtraClass('stacked')
                               ->setRows(30)
                               ->setMode('javascript')
                               ->setTheme('twilight')
                               ->setDescription('Will render in &lt;head /&gt;')
            );

            $fields->addFieldToTab(
                "Root.Code",
                CodeEditorField::create('ExtraTagsFooter', 'Page Specific Footer Tags')
                               ->addExtraClass('stacked')
                               ->setRows(10)
                               ->setMode('html')
                               ->setTheme('twilight')
                               ->setDescription('Use to add extra markup before &lt;/body /&gt; example extra JS files')
            );

            $fields->addFieldToTab(
                "Root.Code",
                CodeEditorField::create('ExtraJSFooter', 'Page Specific JavaScript (Footer)  DO NOT INCLUDE <script></script>')
                               ->addExtraClass('stacked')
                               ->setRows(30)
                               ->setMode('javascript')
                               ->setTheme('twilight')
                               ->setDescription('Will render before &lt;/body /&gt;')
            );

            return $fields;
        }


        function getOGImage() {

            if ($this->FeatureImage()->ID !== 0) {
                return $this->FeatureImage();
            } elseif ($this->HeaderImage()->ID !== 0) {
                return $this->HeaderImage();
            } else {
                return false;
            }

        }
    }
}
